@echo off
setlocal
set starttime=%time%

:: This file execute mesmer executable on several quality assessment files.
:: There are two options to execute this file:
:: The first is the user test mode; simply to confirm that if the files (mesmer.test) generated by current machine
:: is identical to the mesmer baselines.
:: Syntax:
:: C:\MESMER_PATH\MesmerQA>QA

:: The second is developer SVN test mode; it overwrites mesmer.test files in the baseline folders, thus the developer can use
:: SVN check for modifications from the MesmerQA folder to see what files are changed and the detail of the modifications.
:: To use it in the developer mode simply give a -o directive after QA command.
:: Syntax:
:: C:\MESMER_PATH\MesmerQA>QA -o

:: string begins with a period needs to be quoted
SET directive=
SET otfn=mesmer.test
SET executable="../../Windows VC8/Mesmer/Mesmer.exe"
SET tfn=mesmer.test
SET lfn=mesmer.log
SET bline=baselines/Win32/

:: This compares the "double quote" altogether with the content
IF "%1"=="" (
SET directive=-q
SET otfn=test.test
echo -------------------------------------------------------------------------------
echo User QA check mode: output will copy to test.test in the baselines folder.
echo If message "QA test failed" is output, use your own "diff" program to 
echo check changes between test.test and mesmer.test in baseline folders.
echo Please ensure the original files in echo the baseline folders were not
echo previously modified by user.
echo -------------------------------------------------------------------------------
) ELSE (
echo -------------------------------------------------------------------------------
echo Developer QA check mode: output will overwrite the baselines. Use
echo "SVN check for modifications" to check the changes compared with the baselines.
echo -------------------------------------------------------------------------------
)

cd pentyl
%executable% pentyl_isomerization_test.xml %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd HSO2
%executable% HSO2_test.xml %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd "cyclopropene isomerization"
%executable% Cyclopropene_isomerization_test.xml %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd "OH acetylene association"
%executable% OH_acetylene_association_test.xml %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

cd "Acetyl O2 association"
%executable% Acetyl_O2_association.xml %directive%
copy "./%tfn%" "./%bline%%otfn%"
IF "%1"=="-o" copy "./%lfn%" "./%bline%%lfn%"
cd ..

echo Start Time=%starttime% - End Time=%time%

:: This line below makes DOS to create a system Beep (err yup)
echo 
echo 
echo 

